### ISSUE TITLE
sqlite3.OperationalError: no such table: portal_homesetting

### ISSUE THREAD

**Issue by Frank-qlu** [rewrz/RewrZ#3]
你好，后台参数设置，提示找不到表，请问怎么解决？sqlite3.OperationalError: no such table: portal_homesetting

**Comment by rewrz** [comment]
你需要执行以下命令：
python manage.py makemigrations
python manage.py migrate

**Comment by Frank-qlu** [comment]
执行了，还是找不到 Frank Lee 邮箱：lizhipengqilu@gmail.com 签名由 网易邮箱大师 定制 On 12/25/2020 20:29, RewrZ wrote: 你需要执行以下命令： python manage.py makemigrations python manage.py migrate — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rewrz** [comment]
我想你肯定是在后台点了首页设置模块，而这个功能还未开发完整（还没想好要怎么安排UI和键值，哈哈），所以是会报错的。

**Comment by Frank-qlu** [comment]
是的，那我继续完善一下，多谢 Frank Lee 邮箱：lizhipengqilu@gmail.com 签名由 网易邮箱大师 定制 On 12/25/2020 21:23, RewrZ wrote: Closed #3. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
